### ISSUE TITLE
Add ECONNABORTED to retry strategy

### ISSUE THREAD

**Issue by KillWolfVlad** [Byndyusoft/nest-kafka#117]
See https://github.com/axios/axios/issues/1543 for more details

For more questions, ask @bondarenkosa

**Comment by bondarenkosa** [comment]
We can add `ECONNABORTED` retriable code or use `transitional.clarifyTimeoutError = true` in the axios request configuration to convert `ECONNABORTED` to `ETIMEDOUT` status.
